//! Known-answer tests against published vectors.
//!
//! The portfolio claim is "real primitives, no simulated math". These tests are
//! how a reader verifies that claim rather than taking it on trust. Vectors are
//! transcribed from the published specifications, not generated by this crate.

use codetalker_core::kem;
use codetalker_core::{aead, kdf};

fn h(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}

// ---------------------------------------------------------------------------
// RFC 5869 — HKDF-SHA256. All three SHA-256 cases from Appendix A.
// ---------------------------------------------------------------------------

#[test]
fn rfc5869_tc1_basic() {
    let ikm = h("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b");
    let salt = h("000102030405060708090a0b0c");
    let info = h("f0f1f2f3f4f5f6f7f8f9");

    assert_eq!(
        hex::encode(kdf::extract(&salt, &ikm)),
        "077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5"
    );

    let mut okm = [0u8; 42];
    kdf::derive_with_salt(&salt, &ikm, &info, &mut okm).unwrap();
    assert_eq!(
        hex::encode(okm),
        "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865"
    );
}

#[test]
fn rfc5869_tc2_long_inputs() {
    let ikm: Vec<u8> = (0x00u8..=0x4f).collect();
    let salt: Vec<u8> = (0x60u8..=0xaf).collect();
    let info: Vec<u8> = (0xb0u8..=0xff).collect();

    assert_eq!(
        hex::encode(kdf::extract(&salt, &ikm)),
        "06a6b88c5853361a06104c9ceb35b45cef760014904671014a193f40c15fc244"
    );

    let mut okm = [0u8; 82];
    kdf::derive_with_salt(&salt, &ikm, &info, &mut okm).unwrap();
    assert_eq!(
        hex::encode(okm),
        "b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c59045a99cac7827271c\
         b41c65e590e09da3275600c2f09b8367793a9aca3db71cc30c58179ec3e87c14c01d5c1f3434f1d87"
    );
}

#[test]
fn rfc5869_tc3_empty_salt_and_info() {
    let ikm = h("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b");

    assert_eq!(
        hex::encode(kdf::extract(&[], &ikm)),
        "19ef24a32c717b167f33a91d6f648bdf96596776afdb6377ac434c1c293ccb04"
    );

    let mut okm = [0u8; 42];
    kdf::derive_with_salt(&[], &ikm, &[], &mut okm).unwrap();
    assert_eq!(
        hex::encode(okm),
        "8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d201395faa4b61a96c8"
    );
}

// ---------------------------------------------------------------------------
// AES-256-GCM — McGrew & Viega test cases 13 and 14, as carried into the
// NIST GCM specification.
// ---------------------------------------------------------------------------

#[test]
fn gcm_aes256_tc13_empty_plaintext() {
    let key = [0u8; 32];
    let nonce = [0u8; 12];
    let out = aead::seal(aead::Suite::Aes256Gcm, &key, &nonce, b"", b"").unwrap();
    // Empty plaintext, so the output is the tag alone.
    assert_eq!(hex::encode(&out), "530f8afbc74536b9a963b4f1c4cb738b");
}

#[test]
fn gcm_aes256_tc14_single_zero_block() {
    let key = [0u8; 32];
    let nonce = [0u8; 12];
    let out = aead::seal(aead::Suite::Aes256Gcm, &key, &nonce, b"", &[0u8; 16]).unwrap();
    assert_eq!(
        hex::encode(&out),
        "cea7403d4d606b6e074ec5d3baf39d18d0d1c8a799996bf0265b98b5d48ab919"
    );
}

// ---------------------------------------------------------------------------
// ChaCha20-Poly1305 — RFC 8439 §2.8.2.
// ---------------------------------------------------------------------------

#[test]
fn rfc8439_chacha20poly1305_aead() {
    let key: Vec<u8> = (0x80u8..=0x9f).collect();
    let nonce = h("070000004041424344454647");
    let aad = h("50515253c0c1c2c3c4c5c6c7");
    let pt = b"Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would be it.";

    let mut k = [0u8; 32];
    k.copy_from_slice(&key);
    let mut n = [0u8; 12];
    n.copy_from_slice(&nonce);

    let out = aead::seal(aead::Suite::ChaCha20Poly1305, &k, &n, &aad, pt).unwrap();
    assert_eq!(
        hex::encode(&out),
        "d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d63dbea45e8ca9671282fa\
         fb69da92728b1a71de0a9e060b2905d6a5b67ecd3b3692ddbd7f2d778b8c9803aee328091b58fab324e\
         4fad675945585808b4831d7bc3ff4def08e4b7a9de576d26586cec64b61161ae10b594f09e26a7e902e\
         cbd0600691"
    );
}

// ---------------------------------------------------------------------------
// X25519 — RFC 7748 §5.2 and §6.1.
//
// The default build's key agreement rests entirely on this curve, and until
// now it had no published-vector coverage at all: the crate verified its
// symmetric primitives and took the asymmetric ones on trust.
// ---------------------------------------------------------------------------

#[cfg(feature = "classical")]
#[test]
fn rfc7748_x25519_scalar_multiplication() {
    // §5.2, both test vectors.
    let cases = [
        (
            "a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4",
            "e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c",
            "c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552",
        ),
        (
            "4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d",
            "e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493",
            "95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957",
        ),
    ];
    for (scalar, u, expected) in cases {
        assert_eq!(hex::encode(kem::x25519_raw(&h(scalar), &h(u)).unwrap()), expected);
    }
}

#[cfg(feature = "classical")]
#[test]
fn rfc7748_x25519_diffie_hellman() {
    // §6.1: Alice and Bob agree, and the result is the published shared secret.
    let a_sk = h("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a");
    let b_sk = h("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb");
    let a_pk = h("8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a");
    let b_pk = h("de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f");
    let shared = "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742";

    assert_eq!(hex::encode(kem::x25519_base(&a_sk).unwrap()), hex::encode(&a_pk));
    assert_eq!(hex::encode(kem::x25519_base(&b_sk).unwrap()), hex::encode(&b_pk));
    assert_eq!(hex::encode(kem::x25519_raw(&a_sk, &b_pk).unwrap()), shared);
    assert_eq!(hex::encode(kem::x25519_raw(&b_sk, &a_pk).unwrap()), shared);
}

// ---------------------------------------------------------------------------
// Ed25519 — RFC 8032 §7.1.
//
// Peer authentication in the default build is this signature scheme. Same
// story as above: asserted everywhere in the prose, verified against the
// specification nowhere.
// ---------------------------------------------------------------------------

#[cfg(feature = "classical")]
#[test]
fn rfc8032_ed25519_test_vectors() {
    use codetalker_core::identity::{verify, SigSuite};

    // (secret key, public key, message, signature) — TEST 1, TEST 2, TEST 3.
    let cases: [(&str, &str, &str, &str); 3] = [
        (
            "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
            "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
            "",
            "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc6\
             1e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
        ),
        (
            "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
            "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
            "72",
            "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e458\
             f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00",
        ),
        (
            "c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7",
            "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
            "af82",
            "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac18ff9b538d16f290ae6\
             7f760984dc6594a7c15e9716ed28dc027beceea1ec40a",
        ),
    ];

    for (sk_hex, pk_hex, msg_hex, sig_hex) in cases {
        let sig = identity_sign_ed25519(&h(sk_hex), &h(msg_hex));
        assert_eq!(
            hex::encode(&sig),
            sig_hex.replace(['\n', ' '], ""),
            "signature does not match RFC 8032"
        );
        // And the verifier accepts the published signature, not merely its own.
        verify(
            SigSuite::Ed25519,
            &h(pk_hex),
            &h(msg_hex),
            &h(&sig_hex.replace(['\n', ' '], "")),
        )
        .expect("published RFC 8032 signature must verify");
    }
}

/// Sign under a fixed seed. Ed25519 is deterministic, which is what makes a
/// signature KAT possible at all.
#[cfg(feature = "classical")]
fn identity_sign_ed25519(seed: &[u8], msg: &[u8]) -> Vec<u8> {
    use codetalker_core::identity::Identity;
    let s: [u8; 32] = seed.try_into().unwrap();
    Identity::from_ed25519_seed(s).sign(msg).unwrap()
}

// ---------------------------------------------------------------------------
// Negative tests. A cipher that never rejects anything is not a cipher.
// ---------------------------------------------------------------------------

#[test]
fn tag_rejects_bit_flips_everywhere() {
    let key = [0x42u8; 32];
    let nonce = [0x01u8; 12];
    let pt = b"Request immediate air support at grid 214 by 0600.";

    for suite in [aead::Suite::Aes256Gcm, aead::Suite::ChaCha20Poly1305] {
        let ct = aead::seal(suite, &key, &nonce, b"hdr", pt).unwrap();
        assert_eq!(aead::open(suite, &key, &nonce, b"hdr", &ct).unwrap(), pt);

        for i in 0..ct.len() {
            let mut bad = ct.clone();
            bad[i] ^= 0x01;
            assert!(
                aead::open(suite, &key, &nonce, b"hdr", &bad).is_err(),
                "{} accepted a flipped bit at byte {i}",
                suite.name()
            );
        }

        // AAD is bound, not decorative.
        assert!(aead::open(suite, &key, &nonce, b"other", &ct).is_err());
        // Wrong nonce must fail.
        assert!(aead::open(suite, &key, &[0x02u8; 12], b"hdr", &ct).is_err());
        // Wrong key must fail.
        assert!(aead::open(suite, &[0x43u8; 32], &nonce, b"hdr", &ct).is_err());
    }
}

// ---------------------------------------------------------------------------
// ML-DSA-65 (FIPS 204). Peer authentication under `pq`.
//
// The ACVP signature-verification set is the better half of the vectors to
// check, because it carries deliberately invalid cases alongside valid ones: a
// verifier that accepts everything passes a positive-only KAT perfectly.
// ---------------------------------------------------------------------------

#[cfg(feature = "pq")]
#[test]
fn mldsa65_acvp_signature_verification() {
    use codetalker_core::identity::mldsa65_verify_raw;

    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/mldsa65.json");
    let Ok(raw) = std::fs::read_to_string(path) else {
        panic!(
            "FIPS 204 vectors missing at {path}.\n\
             Fetch them before claiming ML-DSA is verified. Fails rather than skips, \
             for the same reason as the ML-KEM vectors above."
        );
    };

    let doc: serde_json::Value = serde_json::from_str(&raw).expect("ACVP file is not valid JSON");
    let (mut accepted, mut rejected, mut skipped) = (0usize, 0usize, 0usize);

    for group in doc["testGroups"].as_array().expect("no testGroups") {
        if group["parameterSet"] != "ML-DSA-65" {
            continue;
        }

        // ACVP covers four interfaces. This crate signs through the pure
        // external one — plain ML-DSA over the message with a context string —
        // so the HashML-DSA and internal-interface groups exercise entry
        // points `identity` does not call. They are counted and reported
        // rather than dropped quietly, because a KAT that silently narrows its
        // own scope is the failure this file exists to avoid.
        let pure_external = group["signatureInterface"] == "external"
            && group["preHash"] == "pure"
            && group["externalMu"] == false;
        if !pure_external {
            skipped += group["tests"].as_array().map_or(0, |t| t.len());
            continue;
        }
        for case in group["tests"].as_array().expect("no tests") {
            let (Some(pk), Some(msg), Some(sig)) = (
                case["pk"].as_str(),
                case["message"].as_str(),
                case["signature"].as_str(),
            ) else {
                continue;
            };
            let ctx = case["context"].as_str().unwrap_or("");
            let should_pass = case["testPassed"].as_bool().unwrap_or(false);

            let got = mldsa65_verify_raw(&h(pk), &h(msg), &h(sig), &h(ctx)).is_ok();
            assert_eq!(
                got,
                should_pass,
                "tcId {} ({}): expected verification to {}",
                case["tcId"],
                case["reason"].as_str().unwrap_or("no reason given"),
                if should_pass { "succeed" } else { "fail" }
            );
            if should_pass {
                accepted += 1
            } else {
                rejected += 1
            }
        }
    }

    // Both directions must be represented. A run that only ever confirmed
    // valid signatures would say nothing about forgery.
    assert!(accepted > 0, "no valid ML-DSA-65 signatures exercised");
    assert!(rejected > 0, "no invalid ML-DSA-65 signatures exercised");
    println!(
        "verified {accepted} valid and {rejected} invalid ML-DSA-65 signatures (FIPS 204); \
         skipped {skipped} cases on interfaces this crate does not use \
         (HashML-DSA, internal, external-mu)"
    );
}

// ---------------------------------------------------------------------------
// ML-KEM (FIPS 203). The vector file is not vendored; CI fetches it.
// This test reports honestly when it is absent rather than silently passing.
// ---------------------------------------------------------------------------

/// Every ML-KEM-768 case in the ACVP file that carries both a decapsulation key
/// and an expected shared secret: the VAL decapsulation groups, and the AFT
/// encapsulation groups, which also publish `dk`, `c` and `k`.
///
/// This checks decapsulation rather than encapsulation because encapsulation
/// draws randomness internally — reproducing a published ciphertext would need
/// the implementation to accept an injected `m`, which `libcrux_kem` does not
/// expose. Decapsulation is deterministic, and it is the direction that matters
/// here: it is the operation the responder performs in `handshake::accept`.
#[cfg(feature = "pq")]
#[test]
fn mlkem768_acvp_vectors() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/mlkem768.json");
    let Ok(raw) = std::fs::read_to_string(path) else {
        panic!(
            "FIPS 203 vectors missing at {path}.\n\
             Fetch them before claiming the PQ path is verified — see README, \
             `Known-answer tests`. This test fails rather than skips on purpose: \
             a silently skipped KAT is worse than no KAT."
        );
    };

    let doc: serde_json::Value = serde_json::from_str(&raw).expect("ACVP file is not valid JSON");
    let groups = doc["testGroups"].as_array().expect("no testGroups");

    let mut checked = 0usize;
    for group in groups {
        if group["parameterSet"] != "ML-KEM-768" {
            continue;
        }
        for case in group["tests"].as_array().expect("no tests") {
            let (Some(dk), Some(ct), Some(k)) = (case["dk"].as_str(), case["c"].as_str(), case["k"].as_str())
            else {
                // Key-check groups carry no ciphertext; nothing to decapsulate.
                continue;
            };

            let got = kem::mlkem768_decapsulate(&h(dk), &h(ct))
                .unwrap_or_else(|e| panic!("tcId {} failed to decapsulate: {e}", case["tcId"]));
            assert_eq!(
                hex::encode(&got),
                k.to_lowercase(),
                "tcId {} shared secret does not match FIPS 203",
                case["tcId"]
            );
            checked += 1;
        }
    }

    // A file that parsed but matched nothing would sail through the loop above
    // and report success, which is the same silent pass the panic exists to
    // prevent. Assert that real vectors were consumed.
    assert!(
        checked >= 30,
        "expected the ACVP file to yield ML-KEM-768 cases, got {checked}"
    );
    println!("verified {checked} ML-KEM-768 decapsulation vectors against FIPS 203");
}
