//! Known-answer tests against published vectors.
//!
//! The portfolio claim is "real primitives, no simulated math". These tests are
//! how a reader verifies that claim rather than taking it on trust. Vectors are
//! transcribed from the published specifications, not generated by this crate.

#[cfg(feature = "pq")]
use codetalker_core::kem;
use codetalker_core::{aead, kdf};

fn h(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}

// ---------------------------------------------------------------------------
// RFC 5869 — HKDF-SHA256. All three SHA-256 cases from Appendix A.
// ---------------------------------------------------------------------------

#[test]
fn rfc5869_tc1_basic() {
    let ikm = h("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b");
    let salt = h("000102030405060708090a0b0c");
    let info = h("f0f1f2f3f4f5f6f7f8f9");

    assert_eq!(
        hex::encode(kdf::extract(&salt, &ikm)),
        "077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5"
    );

    let mut okm = [0u8; 42];
    kdf::derive_with_salt(&salt, &ikm, &info, &mut okm).unwrap();
    assert_eq!(
        hex::encode(okm),
        "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865"
    );
}

#[test]
fn rfc5869_tc2_long_inputs() {
    let ikm: Vec<u8> = (0x00u8..=0x4f).collect();
    let salt: Vec<u8> = (0x60u8..=0xaf).collect();
    let info: Vec<u8> = (0xb0u8..=0xff).collect();

    assert_eq!(
        hex::encode(kdf::extract(&salt, &ikm)),
        "06a6b88c5853361a06104c9ceb35b45cef760014904671014a193f40c15fc244"
    );

    let mut okm = [0u8; 82];
    kdf::derive_with_salt(&salt, &ikm, &info, &mut okm).unwrap();
    assert_eq!(
        hex::encode(okm),
        "b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c59045a99cac7827271c\
         b41c65e590e09da3275600c2f09b8367793a9aca3db71cc30c58179ec3e87c14c01d5c1f3434f1d87"
    );
}

#[test]
fn rfc5869_tc3_empty_salt_and_info() {
    let ikm = h("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b");

    assert_eq!(
        hex::encode(kdf::extract(&[], &ikm)),
        "19ef24a32c717b167f33a91d6f648bdf96596776afdb6377ac434c1c293ccb04"
    );

    let mut okm = [0u8; 42];
    kdf::derive_with_salt(&[], &ikm, &[], &mut okm).unwrap();
    assert_eq!(
        hex::encode(okm),
        "8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d201395faa4b61a96c8"
    );
}

// ---------------------------------------------------------------------------
// AES-256-GCM — McGrew & Viega test cases 13 and 14, as carried into the
// NIST GCM specification.
// ---------------------------------------------------------------------------

#[test]
fn gcm_aes256_tc13_empty_plaintext() {
    let key = [0u8; 32];
    let nonce = [0u8; 12];
    let out = aead::seal(aead::Suite::Aes256Gcm, &key, &nonce, b"", b"").unwrap();
    // Empty plaintext, so the output is the tag alone.
    assert_eq!(hex::encode(&out), "530f8afbc74536b9a963b4f1c4cb738b");
}

#[test]
fn gcm_aes256_tc14_single_zero_block() {
    let key = [0u8; 32];
    let nonce = [0u8; 12];
    let out = aead::seal(aead::Suite::Aes256Gcm, &key, &nonce, b"", &[0u8; 16]).unwrap();
    assert_eq!(
        hex::encode(&out),
        "cea7403d4d606b6e074ec5d3baf39d18d0d1c8a799996bf0265b98b5d48ab919"
    );
}

// ---------------------------------------------------------------------------
// ChaCha20-Poly1305 — RFC 8439 §2.8.2.
// ---------------------------------------------------------------------------

#[test]
fn rfc8439_chacha20poly1305_aead() {
    let key: Vec<u8> = (0x80u8..=0x9f).collect();
    let nonce = h("070000004041424344454647");
    let aad = h("50515253c0c1c2c3c4c5c6c7");
    let pt = b"Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would be it.";

    let mut k = [0u8; 32];
    k.copy_from_slice(&key);
    let mut n = [0u8; 12];
    n.copy_from_slice(&nonce);

    let out = aead::seal(aead::Suite::ChaCha20Poly1305, &k, &n, &aad, pt).unwrap();
    assert_eq!(
        hex::encode(&out),
        "d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d63dbea45e8ca9671282fa\
         fb69da92728b1a71de0a9e060b2905d6a5b67ecd3b3692ddbd7f2d778b8c9803aee328091b58fab324e\
         4fad675945585808b4831d7bc3ff4def08e4b7a9de576d26586cec64b61161ae10b594f09e26a7e902e\
         cbd0600691"
    );
}

// ---------------------------------------------------------------------------
// Negative tests. A cipher that never rejects anything is not a cipher.
// ---------------------------------------------------------------------------

#[test]
fn tag_rejects_bit_flips_everywhere() {
    let key = [0x42u8; 32];
    let nonce = [0x01u8; 12];
    let pt = b"Request immediate air support at grid 214 by 0600.";

    for suite in [aead::Suite::Aes256Gcm, aead::Suite::ChaCha20Poly1305] {
        let ct = aead::seal(suite, &key, &nonce, b"hdr", pt).unwrap();
        assert_eq!(aead::open(suite, &key, &nonce, b"hdr", &ct).unwrap(), pt);

        for i in 0..ct.len() {
            let mut bad = ct.clone();
            bad[i] ^= 0x01;
            assert!(
                aead::open(suite, &key, &nonce, b"hdr", &bad).is_err(),
                "{} accepted a flipped bit at byte {i}",
                suite.name()
            );
        }

        // AAD is bound, not decorative.
        assert!(aead::open(suite, &key, &nonce, b"other", &ct).is_err());
        // Wrong nonce must fail.
        assert!(aead::open(suite, &key, &[0x02u8; 12], b"hdr", &ct).is_err());
        // Wrong key must fail.
        assert!(aead::open(suite, &[0x43u8; 32], &nonce, b"hdr", &ct).is_err());
    }
}

// ---------------------------------------------------------------------------
// ML-KEM (FIPS 203). The vector file is not vendored; CI fetches it.
// This test reports honestly when it is absent rather than silently passing.
// ---------------------------------------------------------------------------

/// Every ML-KEM-768 case in the ACVP file that carries both a decapsulation key
/// and an expected shared secret: the VAL decapsulation groups, and the AFT
/// encapsulation groups, which also publish `dk`, `c` and `k`.
///
/// This checks decapsulation rather than encapsulation because encapsulation
/// draws randomness internally — reproducing a published ciphertext would need
/// the implementation to accept an injected `m`, which `libcrux_kem` does not
/// expose. Decapsulation is deterministic, and it is the direction that matters
/// here: it is the operation the responder performs in `handshake::accept`.
#[cfg(feature = "pq")]
#[test]
fn mlkem768_acvp_vectors() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/mlkem768.json");
    let Ok(raw) = std::fs::read_to_string(path) else {
        panic!(
            "FIPS 203 vectors missing at {path}.\n\
             Fetch them before claiming the PQ path is verified — see README, \
             `Known-answer tests`. This test fails rather than skips on purpose: \
             a silently skipped KAT is worse than no KAT."
        );
    };

    let doc: serde_json::Value = serde_json::from_str(&raw).expect("ACVP file is not valid JSON");
    let groups = doc["testGroups"].as_array().expect("no testGroups");

    let mut checked = 0usize;
    for group in groups {
        if group["parameterSet"] != "ML-KEM-768" {
            continue;
        }
        for case in group["tests"].as_array().expect("no tests") {
            let (Some(dk), Some(ct), Some(k)) = (case["dk"].as_str(), case["c"].as_str(), case["k"].as_str())
            else {
                // Key-check groups carry no ciphertext; nothing to decapsulate.
                continue;
            };

            let got = kem::mlkem768_decapsulate(&h(dk), &h(ct))
                .unwrap_or_else(|e| panic!("tcId {} failed to decapsulate: {e}", case["tcId"]));
            assert_eq!(
                hex::encode(&got),
                k.to_lowercase(),
                "tcId {} shared secret does not match FIPS 203",
                case["tcId"]
            );
            checked += 1;
        }
    }

    // A file that parsed but matched nothing would sail through the loop above
    // and report success, which is the same silent pass the panic exists to
    // prevent. Assert that real vectors were consumed.
    assert!(
        checked >= 30,
        "expected the ACVP file to yield ML-KEM-768 cases, got {checked}"
    );
    println!("verified {checked} ML-KEM-768 decapsulation vectors against FIPS 203");
}
